---
parser: '@babel/eslint-parser'
plugins: [flowtype]
env:
  es6: true
  jest: true

extends:
  - eslint:recommended
  - plugin:flowtype/recommended
  - plugin:react/recommended

globals:
  console: false

settings:
  react:
    version: detect

rules:
  no-param-reassign: 2
  no-shadow: 2
  no-var: 2
  prefer-const: 2

  flowtype/generic-spacing: 0
  flowtype/no-weak-types: 2
  flowtype/require-valid-file-annotation: [2, always]
  # flowtype/space-after-type-colon: 0
